services:
  data-ingestion-service:
    image: waelr1985/data-ingestion-service
    container_name: data-ingestion
    volumes:
      - ./artifacts:/app/artifacts
      - ./key.json:/app/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      - GOOGLE_CLOUD_PROJECT=starlit-byway-436420-s9
    command: python /app/skin/components/data_ingestion/data_ingestion.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  data-validation-service:
    image: waelr1985/data-validation-service
    container_name: data-validation
    depends_on:
      - data-ingestion-service
    volumes:
      - ./artifacts:/app/artifacts
      - ./config:/app/config
    command: python /app/skin/components/data_validation/data_validation.py

  data-transformation-service:
    image: waelr1985/data-transformation-service
    container_name: data-transformation
    depends_on:
      - data-validation-service
    volumes:
      - ./artifacts:/app/artifacts/
    user: root
    command: >
      bash -c "mkdir -p /app/artifacts/transformed_data &&
               chmod -R 777 /app/artifacts &&
               python /app/data_transformation.py --output-dir /app/artifacts/transformed_data"
    restart: on-failure
    
  model-training-service:
    image: waelr1985/model-training-service
    container_name: model-training
    depends_on:
      data-transformation-service:
        condition: service_completed_successfully
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - PYTHONPATH=/app
    command: python /app/model_training.py

  model-evaluation-service:
    image: waelr1985/model-evaluation-service
    container_name: model-evaluation
    depends_on:
      - model-training-service
    volumes:
      - ./artifacts:/app/artifacts
    command: python /app/model_evaluation.py

  model-pusher-service:
    image: waelr1985/model-pusher-service
    container_name: model-pusher
    depends_on:
      - model-evaluation-service
    volumes:
      - ./artifacts:/app/artifacts
      - ./key.json:/app/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      - GOOGLE_CLOUD_PROJECT=starlit-byway-436420-s9
    command: python /app/skin/components/model_pusher/model_pusher.py

  model-predictor-service:
    image: waelr1985/model-predictor
    container_name: model-predictor
    depends_on:
      - model-pusher-service
    volumes:
      - ./artifacts:/app/artifacts
      - ./key.json:/app/credentials/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/key.json
      - B=${B}
      - G=${G}
      - R=${R}
    command: python skin/components/model_predictor/model_predictor.py

  app-service:
    image: waelr1985/app:latest
    container_name: app
    depends_on:
      - data-ingestion-service
      - data-validation-service
      - data-transformation-service
      - model-training-service
      - model-evaluation-service
      - model-pusher-service
      - model-predictor-service
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/config
      - ./key.json:/app/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      - GOOGLE_CLOUD_PROJECT=starlit-byway-436420-s9
    command: uvicorn app:app --host 0.0.0.0 --port 8000