feature_columns:
  - "B"
  - "G"
  - "R"

label_column: "y"

train_test_split:
  train_ratio: 0.8
  test_ratio: 0.2
  seed: 42

model_params:
  numTrees: 100
  maxDepth: 10
  seed: 42

artifact_path: "./artifacts"